[[ -f ~/.config/zsh/oh-my-zsh.zsh ]] && source ~/.config/zsh/oh-my-zsh.zsh
[[ -f ~/.config/zsh/shell-colors.zsh ]] && source ~/.config/zsh/shell-colors.zsh
[[ -f ~/.config/zsh/starship-init.zsh ]] && source ~/.config/zsh/starship-init.zsh
[[ -f ~/.config/zsh/snap-config.zsh ]] && source ~/.config/zsh/snap-config.zsh
[[ -f  ~/.config/zsh/aliases.zsh ]] && source ~/.config/zsh/aliases.zsh
[[ -f  ~/.config/zsh/zsh-highlightings.zsh ]] && source ~/.config/zsh/zsh-highlightings.zsh
[[ -f  ~/.config/zsh/moduler-mojo.zsh ]] && source ~/.config/zsh/moduler-mojo.zsh
[[ -f  ~/.config/zsh/gpg-config.zsh ]] && source ~/.config/zsh/gpg-config.zsh
[[ -f  ~/.config/zsh/bun.zsh ]] && source ~/.config/zsh/bun.zsh
