[zsh.files]
zshrc = { target = "~/.zshrc", type = "symbolic" }

[starship.variables]
primary_color = 202
directory_style = 214

[ghostty.files]
"ghostty/config" = { target = "~/.config/ghostty/config", type = "symbolic" }
