includes = [".dotter/include/windows.toml"]
packages = ["powershell", "starship", "vscode"]

[files]

# For Professional
[variables]
has_work_github = true
# id here is github id
self = { email = "johndoe@example.com", ssh = "~/.ssh/github/id_ed25519_self", id = "johndoe-self" }
work = { email = "johndoe@acme.com", ssh = "~/.ssh/github/id_ed25519_work", id = "johndoe-work" }
languages = ["nodejs", "python", "golang"] # extend this based on starship supported languages

# For Personal
# [variables]
# self = { email = "johndoe@example.com", ssh = "~/.ssh/github/self", id = "johndoe-self" }
